# Dependencies
markdown:         kramdown
highlighter:      pygments

# Gems
plugins:
  - jekyll-gist
  - jekyll-paginate
  - jekyll-seo-tag

# Permalinks
permalink:        pretty

# Setup
title:            Woojin Cho
tagline:          'A Jekyll theme'
description:      'A brazen two-column <a href="http://jekyllrb.com" target="_blank">Jekyll</a> theme that pairs a prominent sidebar with uncomplicated content. Made by <a href="https://twitter.com/mdo" target="_blank">@mdo</a>.'
url:              http://WooJin-Cho.github.io
baseurl:          ""

author:
  name:           'Woojin'
  url:            http://WooJin-Cho.github.io

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde
