# Dependencies
markdown:         kramdown
highlighter:      pygments

# Gems
plugins:
  - jekyll-gist
  - jekyll-paginate
  - jekyll-seo-tag

# Permalinks
permalink:        pretty

# Setup
title:            Woojin
tagline:          '🎹'
description:      'AI researcher'
url:              http://WooJin-Cho.github.io
baseurl:          ""
authorImage:      "/images/IGARSS_presentation.jpeg"
# authorImage:      "/images/woojin.jpg"
# authorImage:      "/images/s3.jpeg"


author:
  name:           'Woojin'
  url:            http://WooJin-Cho.github.io
  email:          woojin.py@gmail.com
paginate:         5

# Custom vars
version:          2.1.0

github:           
  repo:           https://github.com/WooJin-Cho
